version: '3.8'

services:
  app:
    image: ghcr.io/system-analysis-and-design-2023-sut/server:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
