global:
  name: sad-server
  readTimeout: 2m
  readHeaderTimeout: 2m
  writeTimeout: 2m
  idleTimeout: 2m
  maxHeaderBytes: 8196
  apiPort: 8080
  memberlistPort: 8081
  gossopingPort: 8082
  environment: test # supports: "debug" or "release" or "test"
replica:
  hostname:
  - sad-server